name: Download release files

description: Download release files

branding:
  icon: type
  color: purple

inputs:
  release_tag:
    description: "the release tag"
    required: true

runs:
  using: composite
  steps:
    - name: Download release files
      shell: bash
      run: |
        mkdir -pv ${{ runner.temp }}/upload-dir/${{ inputs.release_tag }}
        echo "Start to download release files from MaaRelease..."
        gh release download ${{ inputs.release_tag }} --repo 'MaaAssistantArknights/MaaRelease' --clobber --dir ${{ runner.temp }}/upload-dir/${{ inputs.release_tag }}
        
        echo "Done, folder view:"
        ls -lhA ${{ runner.temp }}/upload-dir/${{ inputs.release_tag }}
