name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup ssh key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_ID }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync repository
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "
              mkdir -p ~/MaaRelease
              cd ~/MaaRelease && git init
              git fetch --force --no-tags --prune --update-head-ok --progress  \
                'https://github.com/${{ github.repository }}' \
                '+HEAD:refs/remotes/origin/HEAD'
              git checkout --force --progress refs/remotes/origin/HEAD
            "
