name: release-mirrors

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  get-files:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Fetch release info"
        run: |
          echo "release_tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: "Download release"
        run: |
          mkdir -pv upload-dir/${{ env.release_tag }}
          cd upload-dir/${{ env.release_tag }}
          gh release download ${{ env.release_tag }} --repo 'MaaAssistantArknights/MaaRelease' --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     - name: "Upload to mirror 0"
  #       uses: appleboy/scp-action@master
  #       with:
  #         host: ${{ secrets.SSH_MIRROR_0_HOST }}
  #         username: ${{ secrets.SSH_MIRROR_0_USER }}
  #         key: ${{ secrets.SSH_MIRROR_0_KEY }}
  #         source: "upload-dir/${{ env.release_tag }}"
  #         target: "/data/html/MaaAssistantArknights/MaaRelease/releases/download"
  #         strip_components: 1
      - name: "Upload to R2"
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          SOURCE_DIR: "upload-dir/${{ env.release_tag }}"
          DEST_DIR: "MaaAssistantArknights/MaaRelease/releases/download"
