name: release-mirrors

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: Release tag (defaults to the tag of the release event)
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.MISTEOWORKFLOW }}
  FILE_PATH: MaaAssistantArknights/MaaRelease/releases/download
  TZ: Asia/Shanghai

jobs:
  # 以下是获取需上传的版本的信息（如果用户手动输入了 release_tag 则改为使用该值）
  getReleaseTag:
    name: Get release tag
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release info
        id: fetchReleaseInfo
        if: ${{ !inputs.release_tag }}
        run: |
          gh release list --repo 'MaaAssistantArknights/MaaRelease' --limit 10 > ${{ runner.temp }}/release_maa
          echo "-------------"
          echo "Last 10 release:"
          column -t ${{ runner.temp }}/release_maa
          head -n 1 ${{ runner.temp }}/release_maa | awk '{ print $1 }' > ${{ runner.temp }}/config
          echo "-------------"
          echo "config:"
          cat ${{ runner.temp }}/config

          echo "release_tag=$(head -n 1 ${{ runner.temp }}/config)" >> $GITHUB_OUTPUT
      - id: getRateLimitStatus
        name: Get rate limit status for current token
        run: |
          export rateLimitStatus=$(gh api /rate_limit | jq -c '.resources.core')
          echo "rateLimitStatus=$rateLimitStatus" >> $GITHUB_OUTPUT
          echo 'Current token rate limit status:'
          echo $rateLimitStatus | jq -r '.reset |= (tostring | tonumber | strflocaltime("%Y-%m-%d %H:%M:%S %Z"))  | to_entries | map([.key, .value]) | .[] | @tsv' | column -t
    outputs:
      release_tag: ${{ inputs.release_tag || steps.fetchReleaseInfo.outputs.release_tag }}
      rateLimitStatus: ${{ steps.getRateLimitStatus.outputs.rateLimitStatus }}

  # 以下开始是各镜像站上传流程。其中：
  #   1. 每个流程均需使用 actions/checkout 获取复用 workflow 文件；
  #   2. 每个流程均需使用 ./.github/downloadReleaseFiles 下载相关版本文件；
  #   3. 如果是支持 S3 api 的对象存储的话，可以用 ./.github/s3Sync 上传；
  #      其他类型也可以自己写上传脚本；
  #   4. 其中 `!contains(needs.getReleaseTag.outputs.release_tag, '.g')` 代表不上传 alpha 版本。
  # 如果需要新增上传流程，需在下方参考其他上传流程和上方说明添加，并在更下方发版流程里按其说明添加依赖。
  ota_server:
    name: Upload to OTA Server
    runs-on: ubuntu-latest
    needs: getReleaseTag
    if: github.repository == 'MaaAssistantArknights/MaaRelease'
    steps:
      - uses: actions/checkout@v3
      - name: Download release files
        id: downloadReleaseFiles
        uses: ./.github/downloadReleaseFiles
        with:
          release_tag: ${{ needs.getReleaseTag.outputs.release_tag }}
          os: windows,linux
          notTempDir: true
      - name: Upload to OTA Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.OTA_SERVER_SSH_HOST }}
          username: ${{ secrets.OTA_SERVER_SSH_USER }}
          key: ${{ secrets.OTA_SERVER_SSH_KEY }}
          source: ${{ steps.downloadReleaseFiles.outputs.dir }}
          target: ${{ format('{0}/{1}', 'OTA', env.FILE_PATH) }}
          strip_components: 1

  R2:
    name: Upload to R2
    runs-on: ubuntu-latest
    needs: getReleaseTag
    if: github.repository == 'MaaAssistantArknights/MaaRelease'
    steps:
      - uses: actions/checkout@v3
      - name: Download release files
        id: downloadReleaseFiles
        uses: ./.github/downloadReleaseFiles
        with:
          release_tag: ${{ needs.getReleaseTag.outputs.release_tag }}
          os: windows,linux
      - name: Upload to R2
        uses: ./.github/s3Sync
        with:
          args: --acl public-read --follow-symlinks
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          SOURCE_DIR: ${{ steps.downloadReleaseFiles.outputs.dir }}
          DEST_DIR: ${{ env.FILE_PATH }}

  AnnAngelaCOS:
    name: Upload to AnnAngela's COS + OBS and fire webhook
    runs-on: ubuntu-latest
    needs: getReleaseTag
    if: (github.repository == 'MaaAssistantArknights/MaaRelease' || github.repository == 'AnnAngela/MaaRelease') && !contains(needs.getReleaseTag.outputs.release_tag, '.g')
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version: lts/*
          check-latest: true
          # cache: npm
      - name: Download release files
        id: downloadReleaseFiles
        uses: ./.github/downloadReleaseFiles
        with:
          release_tag: ${{ needs.getReleaseTag.outputs.release_tag }}
          os: windows
      - name: Prepare the files
        run: node .github/AnnAngela/prepare.js
        env:
          dirWithReleaseTag: ${{ steps.downloadReleaseFiles.outputs.dirWithReleaseTag }}
      - name: Upload to AnnAngela's COS
        run: |
          echo "Installing coscli..."
          gh release download --pattern coscli-linux --dir ${{ runner.temp }}/coscli --clobber --repo tencentyun/coscli
          chmod +x ${{ runner.temp }}/coscli/coscli-linux
          touch ~/.cos.yaml
          echo "coscli installed."
          echo "::group::coscli output"
          ${{ runner.temp }}/coscli/coscli-linux sync ${{ steps.downloadReleaseFiles.outputs.dirWithReleaseTag }} cos://${{ secrets.ANNANGELA_COS_BUCKET }}/MaaRelease --recursive -e cos.accelerate.myqcloud.com -i ${{ secrets.ANNANGELA_COS_SECRET_ID }} -k ${{ secrets.ANNANGELA_COS_SECRET_KEY }}
          echo "::endgroup::"
      - name: Upload to AnnAngela's OBS
        run: |
          echo "Installing obsutil..."
          mkdir ${{ runner.temp }}/obsutil
          wget https://obs-community.obs.cn-north-1.myhuaweicloud.com/obsutil/current/obsutil_linux_amd64.tar.gz --progress=dot:giga -P ${{ runner.temp }}
          tar -xzvf ${{ runner.temp }}/obsutil_linux_amd64.tar.gz -C ${{ runner.temp }}/obsutil
          echo '${{ runner.temp }}/obsutil view:'
          tree -afh ${{ runner.temp }}/obsutil
          export OBSUTIL_FOLDER="${{ runner.temp }}/obsutil/$(ls ${{ runner.temp }}/obsutil | grep -P '^obsutil_linux_amd64_\d+\.\d+\.\d+$')"
          echo "OBSUTIL_FOLDER: $OBSUTIL_FOLDER"
          chmod +x "$OBSUTIL_FOLDER/obsutil"
          touch ~/.obsutilconfig
          echo "obsutil installed."
          echo "::group::obsutil output"
          "$OBSUTIL_FOLDER/obsutil" sync ${{ steps.downloadReleaseFiles.outputs.dirWithReleaseTag }} obs://maa-release/MaaRelease -vmd5 -e obs.cn-south-4.myhuaweicloud.com -i ${{ secrets.ANNANGELA_OBS_SECRET_ID }} -k ${{ secrets.ANNANGELA_OBS_SECRET_KEY }}
          echo "::endgroup::"
      - name: Fire the webhook
        run: |
          node .github/AnnAngela/webhook.js
        env:
          WEBHOOK_URL: https://webhook.annangela.cn/custom?from=MaaRelease
          WEBHOOK_SECRET: ${{ secrets.ANNANGELA_WEBHOOK_SECRET }}
          release_tag: ${{ needs.getReleaseTag.outputs.release_tag }}
          dirWithReleaseTag: ${{ steps.downloadReleaseFiles.outputs.dirWithReleaseTag }}

  MAA_S3:
    name: Upload to MAA S3
    runs-on: ubuntu-latest
    needs: getReleaseTag
    if: github.repository == 'MaaAssistantArknights/MaaRelease'
    steps:
      - uses: actions/checkout@v3
      - name: Download release files
        id: downloadReleaseFiles
        uses: ./.github/downloadReleaseFiles
        with:
          release_tag: ${{ needs.getReleaseTag.outputs.release_tag }}
          os: windows,linux
      - name: Upload to MAA S3
        uses: ./.github/s3Sync
        with:
          args: --acl public-read --follow-symlinks
          AWS_S3_BUCKET: ${{ secrets.MAA_MINIO_RELEASE_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.MAA_MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MAA_MINIO_SECRET_KEY }}
          AWS_REGION: us-east-1
          AWS_S3_ENDPOINT: ${{ secrets.MAA_MINIO_ENDPOINT }}
          SOURCE_DIR: ${{ steps.downloadReleaseFiles.outputs.dir }}
          DEST_DIR: ${{ env.FILE_PATH }}

  R2_MAC:
    name: Upload to R2 mac
    runs-on: macos-13
    needs: getReleaseTag
    if: github.repository == 'MaaAssistantArknights/MaaRelease' && !contains(needs.getReleaseTag.outputs.release_tag, '.g')
    steps:
      - uses: actions/checkout@v3
      - name: Download release files
        id: downloadReleaseFiles
        uses: ./.github/downloadReleaseFiles
        with:
          release_tag: ${{ needs.getReleaseTag.outputs.release_tag }}
          os: macos
      - name: Install Rclone
        run: brew install rclone
      - name: Upload Appcast Packages
        env:
          RCLONE_CONFIG_MAA_TYPE: s3
          RCLONE_CONFIG_MAA_PROVIDER: Cloudflare
          RCLONE_CONFIG_MAA_ACCESS_KEY_ID: ${{ secrets.R2_MAC_KEY_ID }}
          RCLONE_CONFIG_MAA_SECRET_ACCESS_KEY: ${{ secrets.R2_MAC_ACCESS_KEY }}
          RCLONE_CONFIG_MAA_ENDPOINT: ${{ secrets.R2_MAC_ENDPOINT }}
        run: |
          rclone sync ${{ steps.downloadReleaseFiles.outputs.dirWithReleaseTag }} MAA:maa-release/macos
          rclone delete MAA:maa-release/macos --min-age 90d --rmdirs

  # 以下是发版流程，通过触发生成 maa version api 文件的 workflow 发版，。
  # 如果新增了上传流程，除非是像 macOS 一样自行维护发版渠道，
  # 或是 MAA S3 那样上传过久难以等待，否则都应在 needs 里添加新的上传流程的 job id，
  # 避免尚未完成上传就发版导致错误码激增。
  # 最后，新增完上传流程后，除非是像 macOS 一样自行维护发版渠道，
  # 否则都需要到 MaaAssistantArknights/update_version.py 新增镜像地址生成。
  updateVersionApi:
    name: Dispatch the "update_version_api" workflow
    runs-on: ubuntu-latest
    if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    needs:
      - ota_server
      - R2
      - AnnAngelaCOS
      # - MAA_S3 # 太慢了不等他
      # - R2_MAC # 是通过自有渠道发版，不经过 version api
    steps:
      - name: Dispatch the "update_version_api" workflow
        run: gh workflow run update_version_api --repo ${{ github.repository }}
  
  getRateLimitStatus:
    name: Get rate limit status for current token
    runs-on: ubuntu-latest
    if: always()
    needs:
      - getReleaseTag
      - ota_server
      - R2
      - AnnAngelaCOS
      - MAA_S3
      - R2_MAC
      - updateVersionApi
    steps:
      - name: Get rate limit status for current token
        run: |
          echo '${{ needs.getReleaseTag.outputs.rateLimitStatus }}'  > ${{ runner.temp }}/oldRateLimitStatus.json
          gh api /rate_limit | jq -c '.resources.core' > ${{ runner.temp }}/newRateLimitStatus.json
          echo 'Current token rate limit status:'
          jq -r '.reset |= (tostring | tonumber | strflocaltime("%Y-%m-%d %H:%M:%S %Z"))  | to_entries | map([.key, .value]) | .[] | @tsv' ${{ runner.temp }}/newRateLimitStatus.json | column -t
          printf "\n"
          echo "Rate limit used in this action: $(jq -n 'input as $oldRateLimitStatus | input as $newRateLimitStatus | $newRateLimitStatus.used - $oldRateLimitStatus.used' ${{ runner.temp }}/oldRateLimitStatus.json ${{ runner.temp }}/newRateLimitStatus.json)"
