name: update_version_api

on:
  workflow_dispatch:
  release:

jobs:
  update_version_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MISTEOWORKFLOW }}

      - name: Update Version API
        run: |
          python ./MaaAssistantArknights/update_version.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add files to git
        run: |
          git status
          
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .

          commit_msg="chore: Update Version API"
          git commit -m "$commit_msg"

      - name: Push files to github
        run: |
          git push
