name: update-resource

on:
  push:
    paths:
      - .github/workflows/update_resource.yml
  workflow_dispatch:

jobs:
  s3:
    runs-on: ubuntu-latest
    steps:
      - name: Fire the webhook of MAA_S3
        if: github.repository == 'MaaAssistantArknights/MaaRelease'
        run: |
          node scripts/AnnAngela/webhookForJenkins.js
        env:
          WEBHOOK_URL: https://jenkins.maa-org.net/job/maa-resource-s3-sync/buildWithParameters?token=${{ secrets.MAA_JENKINS_PROJECT_TOKEN }}
          WEBHOOK_SECRET: ${{ secrets.MAA_JENKINS_ROBOT_TOKEN }}
  ota:
    runs-on: ubuntu-latest

    steps:
      - name: Setup ssh key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OTA_SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H ${{ secrets.OTA_SERVER_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Update Resource
        run: |
          ssh ${{ secrets.OTA_SERVER_SSH_USER }}@${{ secrets.OTA_SERVER_SSH_HOST }} \
            "
              set -e
              sh ~/MaaRelease/scripts/updateResource.sh
            "
